{"uid":"6c8493acae495f25","name":"test_cursor_no_query","fullName":"tests.unit.async_db.test_cursor#test_cursor_no_query","historyId":"b489e9f0e6d9c2cba4cb912e662cd3f1","time":{"start":1682282281125,"stop":1682282281134,"duration":9},"description":"Some cursor methods are unavailable until a query is run.","descriptionHtml":"<p>Some cursor methods are unavailable until a query is run.</p>\n","status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/allure-results'","statusTrace":"self = <allure_pytest.listener.AllureListener object at 0x7f7c3d3be690>\nfixturedef = <FixtureDef argname='cursor' scope='function' baseid='tests/unit/async_db'>\n\n    @pytest.hookimpl(hookwrapper=True)\n    def pytest_fixture_post_finalizer(self, fixturedef):\n        yield\n        if hasattr(fixturedef, 'cached_result') and self._cache.get(fixturedef):\n            container_uuid = self._cache.pop(fixturedef)\n>           self.allure_logger.stop_group(container_uuid, stop=now())\n\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/allure_pytest/listener.py:174: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/allure_commons/reporter.py:91: in stop_group\n    plugin_manager.hook.report_container(container=group)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/allure_commons/logger.py:39: in report_container\n    self._report_item(container)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/allure_commons/logger.py:30: in _report_item\n    with io.open(self._report_dir / filename, 'w', encoding='utf8') as json_file:\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pyfakefs/fake_filesystem.py:5065: in open\n    newline, closefd, opener)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pyfakefs/fake_filesystem.py:5749: in __call__\n    return self.call(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pyfakefs/fake_filesystem.py:5839: in call\n    real_path)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pyfakefs/fake_filesystem.py:5933: in _init_file_object\n    apply_umask=True)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pyfakefs/fake_filesystem.py:2902: in create_file_internally\n    self.raise_os_error(errno.ENOENT, parent_directory)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pyfakefs.fake_filesystem.FakeFilesystem object at 0x7f7c3cd6c810>\nerr_no = 2\nfilename = '/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/allure-results'\nwinerror = None\n\n    def raise_os_error(self, err_no: int,\n                       filename: Optional[AnyString] = None,\n                       winerror: Optional[int] = None) -> NoReturn:\n        \"\"\"Raises OSError.\n        The error message is constructed from the given error code and shall\n        start with the error string issued in the real system.\n        Note: this is not true under Windows if winerror is given - in this\n        case a localized message specific to winerror will be shown in the\n        real file system.\n    \n        Args:\n            err_no: A numeric error code from the C variable errno.\n            filename: The name of the affected file, if any.\n            winerror: Windows only - the specific Windows error code.\n        \"\"\"\n        message = os.strerror(err_no) + ' in the fake filesystem'\n        if (winerror is not None and sys.platform == 'win32' and\n                self.is_windows_fs):\n            raise OSError(err_no, message, filename, winerror)\n>       raise OSError(err_no, message, filename)\nE       FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/allure-results'\n\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pyfakefs/fake_filesystem.py:1122: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"global_fake_fs","time":{"start":1682282280967,"stop":1682282280970,"duration":3},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"event_loop","time":{"start":1682282280967,"stop":1682282280967,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"description":"Some cursor methods are unavailable until a query is run.","status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/allure-results'","statusTrace":"self = <allure_pytest.listener.AllureListener object at 0x7f7c3d3be690>\nfixturedef = <FixtureDef argname='cursor' scope='function' baseid='tests/unit/async_db'>\n\n    @pytest.hookimpl(hookwrapper=True)\n    def pytest_fixture_post_finalizer(self, fixturedef):\n        yield\n        if hasattr(fixturedef, 'cached_result') and self._cache.get(fixturedef):\n            container_uuid = self._cache.pop(fixturedef)\n>           self.allure_logger.stop_group(container_uuid, stop=now())\n\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/allure_pytest/listener.py:174: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/allure_commons/reporter.py:91: in stop_group\n    plugin_manager.hook.report_container(container=group)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/allure_commons/logger.py:39: in report_container\n    self._report_item(container)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/allure_commons/logger.py:30: in _report_item\n    with io.open(self._report_dir / filename, 'w', encoding='utf8') as json_file:\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pyfakefs/fake_filesystem.py:5065: in open\n    newline, closefd, opener)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pyfakefs/fake_filesystem.py:5749: in __call__\n    return self.call(*args, **kwargs)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pyfakefs/fake_filesystem.py:5839: in call\n    real_path)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pyfakefs/fake_filesystem.py:5933: in _init_file_object\n    apply_umask=True)\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pyfakefs/fake_filesystem.py:2902: in create_file_internally\n    self.raise_os_error(errno.ENOENT, parent_directory)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pyfakefs.fake_filesystem.FakeFilesystem object at 0x7f7c3cd6c810>\nerr_no = 2\nfilename = '/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/allure-results'\nwinerror = None\n\n    def raise_os_error(self, err_no: int,\n                       filename: Optional[AnyString] = None,\n                       winerror: Optional[int] = None) -> NoReturn:\n        \"\"\"Raises OSError.\n        The error message is constructed from the given error code and shall\n        start with the error string issued in the real system.\n        Note: this is not true under Windows if winerror is given - in this\n        case a localized message specific to winerror will be shown in the\n        real file system.\n    \n        Args:\n            err_no: A numeric error code from the C variable errno.\n            filename: The name of the affected file, if any.\n            winerror: Windows only - the specific Windows error code.\n        \"\"\"\n        message = os.strerror(err_no) + ' in the fake filesystem'\n        if (winerror is not None and sys.platform == 'win32' and\n                self.is_windows_fs):\n            raise OSError(err_no, message, filename, winerror)\n>       raise OSError(err_no, message, filename)\nE       FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/allure-results'\n\n/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/pyfakefs/fake_filesystem.py:1122: FileNotFoundError","steps":[],"attachments":[{"uid":"ae36058d76c42082","name":"log","source":"ae36058d76c42082.txt","type":"text/plain","size":824}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"global_fake_fs::0","time":{"start":1682282281154,"stop":1682282281155,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"event_loop::0","time":{"start":1682282281156,"stop":1682282281156,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.unit.async_db"},{"name":"suite","value":"test_cursor"},{"name":"host","value":"fv-az564-589"},{"name":"thread","value":"2345-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.unit.async_db.test_cursor"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"46497e31dcf36668","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/247/712//#testresult/46497e31dcf36668","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/allure-results'","time":{"start":1682282037100,"stop":1682282037107,"duration":7}},{"uid":"83a1a1bc09d921c7","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/247/708//#testresult/83a1a1bc09d921c7","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: '/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/allure-results'","time":{"start":1682280333518,"stop":1682280333525,"duration":7}}]},"tags":["asyncio"]},"source":"6c8493acae495f25.json","parameterValues":[]}